apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - the_project
  - todo_backend/manifests/postgres.yaml
  - todo_backend/manifests/deployment.yaml
  - todo_generator/manifests/cronjob.yaml
