apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: project-image-claim
      containers:
        - name: the-project
          image: elarsaks/the-project:1.12.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: image-cache
              mountPath: /usr/src/app/files
---
apiVersion: v1
kind: Service
metadata:
  name: the-project
spec:
  type: ClusterIP
  selector:
    app: the-project
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the-project
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: the-project
                port:
                  number: 3000
