apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-image-claim
spec:
  storageClassName: project-image
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
