FROM postgres:18.0

RUN apt-get update \
    && apt-get install --no-install-recommends --yes ca-certificates curl gnupg \
    && mkdir --parents /etc/apt/keyrings \
    && curl --fail --silent --show-error https://packages.cloud.google.com/apt/doc/apt-key.gpg \
      | gpg --dearmor --output /etc/apt/keyrings/cloud.google.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
      > /etc/apt/sources.list.d/google-cloud-sdk.list \
    && apt-get update \
    && apt-get install --no-install-recommends --yes google-cloud-cli \
    && rm -rf /var/lib/apt/lists/*
