apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/configmap.yaml
- manifests/deployment.yaml

images:
- name: elarsaks/log-output
  newName: elarsaks/log-output
  newTag: 2ff9cddce88b469bee03f4fd6cb5d47bad76e7b1
