apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-production

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: broadcaster-config.yaml
  - path: broadcaster-generic.yaml

images:
  - name: PROJECT/IMAGE
    newName: elarsaks/the-project
    newTag: base
  - name: elarsaks/todo-backend
    newTag: base
  - name: elarsaks/todo-generator
    newTag: base
  - name: elarsaks/todo-broadcaster
    newTag: base
  - name: elarsaks/todo-postgres-backup
    newName: elarsaks/todo-postgres-backup
    newTag: base
